# Site settings
title: Marco Margaritoff
email: marcomc2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/marco" # the subpath of your site, e.g. /blog/
url: "http://marcomargaritoff.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
